# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPW3AdFE8VEWzU4tI2bDXkbIdChAeajC
"""

import sys
import random
import math
import numpy as np
from numba import njit

def calculate_fitness(schedule):
    return len(schedule)

@njit
def fast_insertion(c, m_duration, possible_teachers, starts, class_busy, teacher_busy):
    for i in range(len(starts)):
        st = starts[i]

        c_conflict = False
        for p in range(st, st + m_duration):
            if class_busy[c, p] == 1:
                c_conflict = True
                break
        if c_conflict:
            continue

        for j in range(len(possible_teachers)):
            t = possible_teachers[j]
            t_conflict = False
            for p in range(st, st + m_duration):
                if teacher_busy[t, p] == 1:
                    t_conflict = True
                    break

            if not t_conflict:
                return st, t

    return -1, -1

def solve():
    input_data = sys.stdin.read().split()
    if not input_data:
        return

    idx = 0
    T = int(input_data[idx])
    N = int(input_data[idx+1])
    M = int(input_data[idx+2])
    idx += 3

    class_subjects_list = []
    for i in range(1, N + 1):
        while True:
            val = int(input_data[idx])
            idx += 1
            if val == 0: break
            class_subjects_list.append((i, val))

    teacher_skills = {}
    for t in range(1, T + 1):
        skills = []
        while True:
            val = int(input_data[idx])
            idx += 1
            if val == 0: break
            skills.append(val)
        teacher_skills[t] = set(skills)

    durations = {}
    for m in range(1, M + 1):
        durations[m] = int(input_data[idx])
        idx += 1

    teachers_for_subject = {}
    for m in range(1, M + 1):
        t_list = [t for t in range(1, T + 1) if m in teacher_skills[t]]
        teachers_for_subject[m] = np.array(t_list, dtype=np.int32)

    valid_starts_arr = {}
    for m in range(1, M + 1):
        d = durations[m]
        starts = []
        for s in range(10):
            for p in range(1, 7 - d + 1):
                starts.append(s * 6 + p)
        valid_starts_arr[m] = np.array(starts, dtype=np.int32)

    current_schedule = {}
    class_busy = np.zeros((N + 1, 61), dtype=np.int8)
    teacher_busy = np.zeros((T + 1, 61), dtype=np.int8)

    unassigned = list(class_subjects_list)
    random.shuffle(unassigned)

    for c, m in unassigned:
        p_teachers = np.copy(teachers_for_subject[m])
        np.random.shuffle(p_teachers)
        p_starts = np.copy(valid_starts_arr[m])
        np.random.shuffle(p_starts)

        st, t = fast_insertion(c, durations[m], p_teachers, p_starts, class_busy, teacher_busy)
        if st != -1:
            current_schedule[(c, m)] = (st, t)
            class_busy[c, st:st+durations[m]] = 1
            teacher_busy[t, st:st+durations[m]] = 1

    best_schedule = dict(current_schedule)

    temp = 100.0
    cooling_rate = 0.99
    iterations = 2000
    destroy_ratio = 3

    for _ in range(iterations):
        neighbor_schedule = dict(current_schedule)
        neighbor_class_busy = np.copy(class_busy)
        neighbor_teacher_busy = np.copy(teacher_busy)

        assigned_keys = list(neighbor_schedule.keys())

        if assigned_keys:
            num_remove = random.randint(1, min(len(assigned_keys), max(1, len(assigned_keys) // destroy_ratio)))
            removed_keys = random.sample(assigned_keys, num_remove)
            for k in removed_keys:
                c, m = k
                st, t = neighbor_schedule[k]
                d = durations[m]
                neighbor_class_busy[c, st:st+d] = 0
                neighbor_teacher_busy[t, st:st+d] = 0
                del neighbor_schedule[k]

        unassigned_now = [x for x in class_subjects_list if x not in neighbor_schedule]
        random.shuffle(unassigned_now)

        for c, m in unassigned_now:
            p_teachers = np.copy(teachers_for_subject[m])
            np.random.shuffle(p_teachers)
            p_starts = np.copy(valid_starts_arr[m])
            np.random.shuffle(p_starts)

            st, t = fast_insertion(c, durations[m], p_teachers, p_starts, neighbor_class_busy, neighbor_teacher_busy)
            if st != -1:
                neighbor_schedule[(c, m)] = (st, t)
                neighbor_class_busy[c, st:st+durations[m]] = 1
                neighbor_teacher_busy[t, st:st+durations[m]] = 1

        current_fit = calculate_fitness(current_schedule)
        neighbor_fit = calculate_fitness(neighbor_schedule)
        delta = neighbor_fit - current_fit

        if delta > 0 or random.random() < math.exp(delta / temp):
            current_schedule = dict(neighbor_schedule)
            class_busy = np.copy(neighbor_class_busy)
            teacher_busy = np.copy(neighbor_teacher_busy)
            current_fit = neighbor_fit

            if current_fit > calculate_fitness(best_schedule):
                best_schedule = dict(current_schedule)

        temp *= cooling_rate

    print(len(best_schedule))

    for (c, m) in sorted(best_schedule.keys()):
        st, t = best_schedule[(c, m)]
        print(f"{c} {m} {st} {t}")

if __name__ == '__main__':
    solve()